-- ------------------------------------------------------------------- --
-- HANDCRAFTED FILE (experimental). Will become autogenerated once the --
-- subtitle texts are collected and the Crowdin pipeline is extended.  --
-- ------------------------------------------------------------------- --

local _, addonTable = ...

addonTable.subtitle = {
    -- movies: [movie id] = { [subtitle order] = translation }
    -- order follows the client subtitle files (Movie.db2 SubtitleFileDataID -> .sbt)
    movie = {
        [2] = { -- wow intro
            [1] = "Чотири роки минуло відтоді, як смертні раси об'єдналися і разом постали проти могутності Палаючого Легіону.",
            [2] = "Хоча Азерот було врятовано, хисткий пакт між Ордою та Альянсом майже розвіявся.",
            [3] = "Барабани війни гримлять знову.",
        },
        [27] = { -- tbc intro
            [1] = "Ув'язнений десять тисяч років.",
            [2] = "Вигнаний з власної батьківщини.",
            [3] = "І тепер ви смієте вступати до МОЇХ володінь.",
            [4] = "Ви не готові.",
            [5] = "ВИ НЕ ГОТОВІ!",
        },
    },

    -- in-engine cinematics and any other subtitle lines: [english text (trimmed)] = translation
    text = {
    },
}
