-- ------------------------------------------------------------------- --
-- HANDCRAFTED FILE (experimental). Will become autogenerated once the --
-- subtitle texts are collected and the Crowdin pipeline is extended.  --
-- ------------------------------------------------------------------- --

local _, addonTable = ...

addonTable.subtitle = { -- [english text] = text
-- wow intro movie (movie id 2), first line; used to verify the mechanism e2e,
-- the exact english text must match what SHOW_SUBTITLE delivers
["Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion."] = "Чотири роки минуло відтоді, як смертні раси об'єдналися і разом постали проти могутності Палаючого Легіону.",
}
