-- ------------------------------------------------------------------- --
-- HANDCRAFTED FILE (experimental). Will become autogenerated once the --
-- subtitle texts are collected and the Crowdin pipeline is extended.  --
-- ------------------------------------------------------------------- --

local _, addonTable = ...
-- TRANSLATION ARE AI-GENERATED FOR TESTING PURPOSES

local subtitle = {
    intro = {
        -- TIMINGS ARE NOT CALIBRATED YET
        Worgen = {
            map = 202, -- Gilneas City (same id on cata and mists clients)
            -- Led by their indomitable king, Genn Greymane, the proud citizens of Gilneas once stood with the Alliance against the vile orcish Horde that sought to conquer all of Lordaeron.
            { 0, 12, "Очолювані своїм незламним королем Ґенном Сивогривом, горді громадяни Ґілнеасу колись стояли разом з Альянсом проти мерзенної орди орків, що прагнула підкорити весь Лордерон." },
            -- Gilneas survived but, in the years following the Second War, the kingdom drew ever inward.
            { 12, 19, "Ґілнеас вистояв, але в роки після Другої війни королівство дедалі більше замикалося в собі." },
            -- Distrustful of their former allies, the Gilneans erected a mighty wall at the borders of their land, closing off their nation - and their hearts - from an ever-darkening world.
            { 19, 31, "Не довіряючи колишнім союзникам, ґілнеасці звели могутню стіну на кордонах своєї землі, відгородивши свою націю — і свої серця — від світу, що поринав у темряву." },
            -- Now, many years later, as the seemingly unstoppable undead Scourge marches across Lordaeron, human civilization once again teeters on the edge of destruction.
            { 31, 42, "Тепер, багато років по тому, коли, здавалося б, нездоланна нежить Скари крокує Лордероном, людська цивілізація знову балансує на межі знищення." },
            -- As war and terror close in all around them, the citizens of Gilneas are faced with one, terrible truth: their mighty wall cannot hold back the dead for much longer...
            { 42, 53, "Поки війна і жах підступають зусібіч, громадяни Ґілнеасу постали перед однією страшною правдою: їхня могутня стіна вже недовго стримуватиме мертвих..." },
            -- ...and, worse, rumors of a new threat have risen within the kingdom's borders of feral, nightmare creatures that walk upright as men but hunt and howl as wolves.
            { 53, 65, "...а що гірше — у межах королівства ширяться чутки про нову загрозу: диких кошмарних істот, які ходять на двох ногах, мов люди, але полюють і виють, мов вовки." },
        },
        Goblin = {
            map = 194, -- Kezan (same id on cata and mists clients)
            -- The wily cunning goblins of Kezan have lived in relative peace for generations.
            { 0, 8, "Хитрі та кмітливі гобліни Кезану поколіннями жили у відносному мирі." },
            -- Though some of their race sided with the marauding orcs during the Second War, most goblins remained neutral throughout the various conflicts between the Alliance and Horde.
            { 8, 19, "Хоча дехто з їхнього роду став на бік орків-грабіжників під час Другої війни, більшість гоблінів зберігала нейтралітет у конфліктах між Альянсом та Ордою." },
            -- Ruled over by corrupt yet highly affluent Trade Princes, the goblins created a virtual paradise for themselves throughout the islands of the South Seas.
            { 19, 30, "Під владою продажних, але надзвичайно заможних торгових принців гобліни створили собі справжній рай на островах Південних морів." },
            -- Their ingenious feats of engineering and vast trade fleets helped make their island capital of Kezan one of the great technological wonders of the world.
            { 30, 41, "Їхні геніальні інженерні винаходи та величезні торгові флоти зробили їхню острівну столицю Кезан одним із найбільших технологічних див світу." },
            -- But now, as the elements themselves rise up in anger across the world, the goblins' mechanical paradise will be put to the test.
            { 41, 50, "Але тепер, коли самі стихії гнівно повстають по всьому світу, на механічний рай гоблінів чекає випробування." },
            -- For very soon, fate will force them to choose sides in a conflict that will shape the very history of the world.
            { 50, 60, "Адже вже зовсім скоро доля змусить їх обрати сторону в конфлікті, що визначить саму історію світу." },
        },
    },
}

-- newer expansion files add or override entries per movie id / text key / race
if addonTable.subtitle then
    for k, v in pairs(subtitle) do
        if type(addonTable.subtitle[k]) == "table" and type(v) == "table" then
            for vk, vv in pairs(v) do
                addonTable.subtitle[k][vk] = vv
            end
        else
            addonTable.subtitle[k] = v
        end
    end
else
    addonTable.subtitle = subtitle
end
